name: Build and Pack

# Controls when the workflow will run
on:
  push:
    branches:
      - Main
    paths:
      - "FoxSitesInformation/**"
  pull_request:
    types: [closed]
    branches:
      - Main
    paths:
      - "FoxSitesInformation/**"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel

jobs:
  Packaging:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v2

      - name: Insert Required Modules
        working-directory: ./FoxSitesInformation
        run: |
          $Modules=Import-Csv -Path .\Modules\PlaceHolderForModules.txt
          Foreach ($Module in $Modules){
          $Module=$Module -replace '@{Modules=','' -replace '}',''
          Write-Output -InputObject "Saving $Module"
          Find-module -Name $Module  | Save-Module -Path .\Modules -Verbose
          'Verifying Module was saved successfully'
          test-path -path .\Modules\$Module}
        shell: pwsh

      - name: Create Zip
        working-directory: .
        run: |
          'Compressing to Zip File'
          Compress-Archive -Path .\FoxSitesInformation -DestinationPath .\FoxSitesInformation.zip -CompressionLevel Optimal
          'Testing Zip creation'
          test-path -path .\FoxSitesInformation.zip
        shell: pwsh

      - name: Upload Release to Github Repository
        uses: svenstaro/upload-release-action@v2
        with:
          file: .\FoxSitesInformation.zip
          asset_name: FoxSitesInformation.zip
          tag: Release
