
name: Build and Pack

# Controls when the workflow will run
on:
  push:
    branches:
      - Main
    paths:
      - 'FoxSitesInformation/**'
  pull_request:
    types: [closed]
    branches:
      - Main
    paths:
      - 'FoxSitesInformation/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel

jobs:
  psgallery_publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        
      - name: Publishing
        working-directory: .
        env:
         NUGET_KEY: ${{ secrets.NUGET_KEY }}
        run: |
          

        shell: pwsh
