name: Build and Pack

# Controls when the workflow will run
on:
  push:
    branches:
      - Main
    paths:
      - "FoxSitesInformation/**"
  pull_request:
    types: [closed]
    branches:
      - Main
    paths:
      - "FoxSitesInformation/**"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel

jobs:
  Packaging:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Insert Required Modules
        working-directory: .\FoxSitesInformation
        env:
          NUGET_KEY: ${{ secrets.NUGET_KEY }}
        run: |
          $Modules=Import-Csv -Path .\Modules\PlaceHolderForModules.txt
          Foreach ($Module in $Modules){
          $Module=$Module -replace '@{Modules=','' -replace '}',''
          Write-Output -InputObject "Saving $Module"
          Find-module -Name $Module  | Save-Module -Path .\Modules -Verbose
          }

        shell: PowerShell
