name: Build and Pack

# Controls when the workflow will run
on:
  push:
    branches:
      - Main
    paths:
      - "FoxSitesInformation/**"
  pull_request:
    types: [closed]
    branches:
      - Main
    paths:
      - "FoxSitesInformation/**"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel

jobs:
  Packaging:
    runs-on: ubuntu-latest
    steps:
      - name: Creating Environments
        uses: actions/checkout@v2

      - name: Insert Required Modules
        working-directory: ./FoxSitesInformation
        run: |
          $Modules=Import-Csv -Path .\Modules\PlaceHolderForModules.txt
          Foreach ($Module in $Modules){
          $Module=$Module -replace '@{Modules=','' -replace '}',''
          Write-Output -InputObject "Saving $Module"
          Find-module -Name $Module  | Save-Module -Path .\Modules -Verbose
          'Verifying Module was saved successfully'
          test-path -path .\Modules\$Module
          }
        shell: pwsh

      - name: Compile EXE
        working-directory: .
        run: |
          Try{
          'Installing Module PS2EXE'
          Install-Module -Name ps2exe -force
          'Creating EXE'
          Invoke-PS2EXE -inputFile .\FoxSitesInformation\Get-FoxSitesInformation.ps1 -outputFile .\FoxSitesInformation\Get-FoxSitesInformation.exe -iconFile .\ExternalResources\Icon\Favicon.ico  -title 'Fox Sites Information Generator' -version 1 -requireAdmin -Verbose
          'Verifying Existance of EXE'
          test-path -path .\FoxSitesInformation\Get-FoxSitesInformation.exe}
          Catch {
          Write-host "An Error occured during creation of EXE. See full expection below.`nExecption:"$Error[0].Exception"`nTargetObject:"$Error[0].TargetObject"`nInvocationInfo:"$Error[0].InvocationInfo -ForegroundColor Red
          }
        shell: pwsh

      - name: Create Zip
        working-directory: .
        run: |
          'Compressing to Zip File'
          Compress-Archive -Path .\FoxSitesInformation -DestinationPath .\FoxSitesInformation.zip -CompressionLevel Optimal -Verbose
        shell: pwsh

      - name: Prepare to upload release
        run: cargo build --release --locked

      - name: Upload Release to Github Repository
        uses: svenstaro/upload-release-action@v2
        with:
          file: .\FoxSitesInformation\Get-FoxSitesInformation.exe
          asset_name: Get-FoxSitesInformation.exe
          tag: Zip
